clientSender.email=noreply@mera-asistani.local
support.email=destek@mera-asistani.local
revenueCat.googleApiKey=disabled
revenueCat.appleApiKey=disabled
mailjet.apiKey=disabled
mailjet.secretKey=disabled
